apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
stringData:
  admin-user: admin
  admin-password: supersecurepassword123