# playbooks/01_deploy_sealed_secrets.yml
- name: 🚀 Instalar Sealed Secrets Controller en el clúster
  hosts: controller
  become: true
  gather_facts: false

  vars_files:
    - ../vars/main.yml

  roles:
    - sealed_secrets
