# playbooks/install_sealed_secrets.yml
- name: Instalar Sealed Secrets Controller
  hosts: controller
  become: true
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  roles:
    - sealed_secrets

---
- name: Instalar kubeseal CLI localmente
  hosts: localhost
  become: true
  gather_facts: false
  roles:
    - kubeseal_cli_local_installer
