# playbooks/install_sealed_secrets.yml
- name: Instalar Sealed Secrets Controller
  hosts: controller
  become: true
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  roles:
    - sealed_secrets

---
- name: Instalar kubeseal localmente
  hosts: localhost
  become: true
  roles:
    - kubeseal_installer

---
- name: Crear directorio temporal
  tempfile:
    state: directory
    suffix: kubeseal
  register: tmpdir

- name: Descargar kubeseal v0.24.6
  get_url:
    url: "https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.6/kubeseal-0.24.6-linux-amd64.tar.gz"
    dest: "{{ tmpdir.path }}/kubeseal.tar.gz"
    mode: '0644'

- name: Extraer kubeseal
  unarchive:
    src: "{{ tmpdir.path }}/kubeseal.tar.gz"
    dest: "{{ tmpdir.path }}"
    remote_src: yes

- name: Instalar kubeseal en /usr/local/bin
  copy:
    src: "{{ tmpdir.path }}/kubeseal"
    dest: /usr/local/bin/kubeseal
    mode: '0755'
    remote_src: yes

- name: Verificar versión instalada
  command: kubeseal --version
  register: kubeseal_version
  changed_when: false

- name: Mostrar versión de kubeseal
  debug:
    var: kubeseal_version.stdout
